### ISSUE TITLE
[Little Fix] Doesn't show the link that's supposed to send to the victim

### ISSUE THREAD

**Issue by Himan10** [krishpranav/IP-Grabber#10]
I recently came across this GitHub repo and found it quite straight-forward to use, I thought to give it a try once just to understand how you've done that. 

I installed the GitHub repo. in my local environment and as per the tutorial posted by you in the video format, I ran the ngrok on another terminal but still, it didn't print the IP address. 

![image](https://github.com/krishpranav/IP-Grabber/assets/33115688/2cf1ec64-9216-4c7f-b932-ab1d89ced5c4)

I thought it might be an update problem with ngrok, but even after updating the ngrok, I was still not getting the IP Address displayed on the terminal, so I checked the code and found out there was an issue with the statement on line 250 i.e., 
`link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "https://[0-9a-z]*\.ngrok.io")`

Because the version of ngrok I am using (and the one downloaded by yours) doesn't have the "ngrok.io" at the end of the URL which is supposed to send to the victim, instead I got "ngrok.free.app", or even if in future there's anything other than this top-level or second-level domain, then it'd be useful. 
For example: 

```sh
┌──[hi-man@blackHat ~]
└──$ >> curl http://127.0.0.1:4040/api/tunnels
{"tunnels":[{"name":"command_line","ID":"10c00c4370bf54be4dae5a9329a5e955","uri":"/api/tunnels/command_line","public_url":"https://2d48-2409-xxxx-xxx-xxxx-xxxx-xxxx-xxxx-1aff.ngrok-free.app","proto":"https","config":{"addr":"http://localhost:80","inspect":true},"metrics":{"conns":{"count":0,"gauge":0,"rate1":0,"rate5":0,"rate15":0,"p50":0,"p90":0,"p95":0,"p99":0},"http":{"count":0,"rate1":0,"rate5":0,"rate15":0,"p50":0,"p90":0,"p95":0,"p99":0}}}],"uri":"/api/tunnels"}

┌──[hi-man@blackHat ~]
└──$ >> curl -s http://127.0.0.1:4040/api/tunnels | grep -Po "https://[\w\.\-]+"
https://2d48-2409-xxxx-xxx-xxxx-xxxx-xxxx-xxxx-1aff.ngrok-free.app
```

As you can see, using this regex pattern, it prints out the IP address, hence in the terminal as well. 

![image](https://github.com/krishpranav/IP-Grabber/assets/33115688/bb4f92f8-6a53-441e-b04e-f9a5735f2770)

![image](https://github.com/krishpranav/IP-Grabber/assets/33115688/4fb85a0a-d6f4-49fe-af35-c7b2e12988a1)

Also, there isn't any need of running `ngrok` alongside the bash script. I am on Linux, and it's works perfectly fine for me without running `ngrok`, so probably these changes might work for others too on different O.S.

**Comment by krishpranav** [comment]
this fix looks good, would be great if you raise a PR with this fix.

**Comment by Himan10** [comment]
Sure, I'll raise a new PR for this including other changes as well.
