### ISSUE TITLE
It doesn't show the link and says "Using urlshortner: Error". I am on Mac Big Sur 11.2.3

### ISSUE THREAD

**Issue by kollonn** [krishpranav/IP-Grabber#3]
<img width="563" alt="Skärmavbild 2021-08-03 kl  16 28 56" src="https://user-images.githubusercontent.com/82838009/128033225-dfa1b7d1-fbb2-4e51-b9ab-f97a2b32f60d.png">

**Comment by krishpranav** [comment]
hey hi @kollonn so are you using this tool on any linux system or termux?

**Comment by krishpranav** [comment]
hey hi @kollonn so your using this tool on Mac right??

**Comment by krishpranav** [comment]
follow the steps I am giving

**Comment by krishpranav** [comment]
so you need to download these tools require for Macos:
```
brew install wget
brew install curl
```

**Comment by krishpranav** [comment]
for Macos you need to download ngork manually from ngrok.com

**Comment by krishpranav** [comment]
before running bash ip-grabber.sh open a new window and type ngrok http 3333

**Comment by krishpranav** [comment]
you will get the link

**Comment by krishpranav** [comment]
![Untitled](https://user-images.githubusercontent.com/68631244/128113712-c4036cd9-a640-4755-90d4-e7259cbaa288.jpg)

**Comment by krishpranav** [comment]
after following these steps you will get result!

**Comment by kollonn** [comment]
I followed all the steps you said but i still get stuck on downloading ngrok in "ip-grabber.sh". I think that ngrok is installed but the script tries to install it and fails for some reason, so then it can't proceed to the next step.

**Comment by Vectorworkz** [comment]
> after following these steps you will get result!

My phishing link was not working second time. Why?

**Comment by krishpranav** [comment]
> I followed all the steps you said but i still get stuck on downloading ngrok in "ip-grabber.sh". I think that ngrok is installed but the script tries to install it and fails for some reason, so then it can't proceed to the next step.

download ngrok from they're site and 
./ngrok http 3333
after executing this command 
type
bash ip-grabber.sh

**Comment by krishpranav** [comment]
I am also in macOS Big Sur but I for me it works fine

**Comment by krishpranav** [comment]
> > after following these steps you will get result!
> 
> My phishing link was not working second time. Why?

can you send me the screenshot of it?? @Vectorworkz

**Comment by kollonn** [comment]
i just get the same error after following the steps

**Comment by Vectorworkz** [comment]
> > > after following these steps you will get result!
> > 
> > My phishing link was not working second time. Why?
> 
> can you send me the screenshot of it?? @Vectorworkz 

I will sent morning

**Comment by Vectorworkz** [comment]
> > > after following these steps you will get result!
> > 
> > My phishing link was not working second time. Why?
> 
> can you send me the screenshot of it?? @Vectorworkz 

- [ ] ![IMG-20210804-WA0052.jpg](https://user-images.githubusercontent.com/88365932/128182158-92b6702c-fe02-4f1b-aa0f-cbc87c64e6f3.jpg)

**Comment by krishpranav** [comment]
> i just get the same error after following the steps

oh ok

**Comment by krishpranav** [comment]
> i just get the same error after following the steps

I will record the steps and send you

**Comment by Vectorworkz** [comment]
> > i just get the same error after following the steps
> 
> I will record the steps and send you

Ok

**Comment by krishpranav** [comment]
https://user-images.githubusercontent.com/68631244/128188421-eae957f2-20c5-41fe-bc70-24e37b3d86e5.mov

**Comment by krishpranav** [comment]
> IP-Grabber.mov

@kollonn see the steps I done
for me it works fine!!
