### ISSUE TITLE
Doesn't show link but I have photos of issue

### ISSUE THREAD

**Issue by Spartan76** [krishpranav/IP-Grabber#8]
![Screenshot_2022-11-06-14-43-00-927_com.termux.jpg](https://user-images.githubusercontent.com/105983195/200174246-4645fe9d-0e43-4ece-8e81-fb6fc767238c.jpg)

![Screenshot_2022-11-06-14-42-51-490_com.termux.jpg](https://user-images.githubusercontent.com/105983195/200174256-0ef41adb-71f8-44ad-aaba-858ca399f177.jpg)
 
As you can see i opened the http for ngrok in another window of the terminal as you suggested but the link doesn't show

**Comment by Spartan76** [comment]
Another session or another terminal that is not termux?

**Comment by krishpranav** [comment]
you can use the prehosted ngrok link, the tool autmatically uses the pre hosted ngrok link

**Comment by krishpranav** [comment]
take the latest pull we have done some enlargements.
